version: "3.9"

networks:
  default:
    name: backend-lesson

services:
  web:
    image: node:17.4.0
    environment:
      - PORT=3000
      - NODE_ENV=development
    extra_hosts: # For Linux
      - "host.docker.internal:host-gateway"
    ports:
      - 3000:3000
    tty: true
    user: "node"
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    expose:
      - "3000"
    # command: "npm run dev"
